# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLikelihood <- function(covar_params, nu, Ga, Z, delta, cent, s2, T_i, dd, ni, N) {
    .Call(`_skewtlmm_fastLikelihood`, covar_params, nu, Ga, Z, delta, cent, s2, T_i, dd, ni, N)
}

